### ISSUE TITLE
Run on issue/PR close

### ISSUE THREAD

**Issue by hkdobrev** [instantish/milestone-closer#6]
Couldn't the action run on issue/PR close, check if there is a milestone set and check if that milestone should be closed?

This would surely save build minutes as it wouldn't run 24/7, but only when there's closing activity and it wouldn't iterate through every milestone each time.

**Comment by marissamarym** [comment]
I considered that approach initially- it would have to run on `issue` `close`/`open`/`milestone`/`demilestone`/`transfer` and `pr` `close`/`open`/`milestone`/`demilestone`.

So it might be running pretty often for those 9 events, and bulk actions like selecting many issues would trigger many events. If you have 1000s of issues, it could trigger a lot of actions pretty often.

Definitely worth adding an option for that though, for repos that have few issues. Or it could detect the number of issues and choose a strategy to keep the action minutes as low as possible. The tradeoff with that is it might be more confusing to the user as to what's going on.
